# .streamlit/secrets.toml

[connections.postgresql] 
dialect = "postgresql"
server = "swafxjmhzpoozhccsvzv.supabase.co" # ENDEREÃ‡O OBTIDO
database = "postgres"
username = "postgres"
password = "_GJ$e5drTfRR6Yi" # SENHA OBTIDA
